import { motion } from 'motion/react'
import { ArrowRight, BarChart3, Check, ChevronRight, CircleDollarSign, Menu, PieChart, ReceiptText, ShieldCheck, Sparkles, WalletCards, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useState } from 'react'

const features = [
  { icon: CircleDollarSign, title: 'Income Tracking', text: 'See every stream of income in one calm, clear view.' },
  { icon: ReceiptText, title: 'Expense Tracking', text: 'Know exactly where your money goes, without the guesswork.' },
  { icon: WalletCards, title: 'Budget Management', text: 'Set flexible budgets that keep your goals on track.' },
  { icon: BarChart3, title: 'Spending Analytics', text: 'Turn daily spending into insights you can act on.' },
  { icon: ShieldCheck, title: 'Transaction History', text: 'A searchable, organized record of every financial move.' },
  { icon: PieChart, title: 'Monthly Reports', text: 'Understand your month at a glance with thoughtful reports.' },
]

function DashboardPreview() {
  return <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, delay: .2 }} className="relative mx-auto max-w-5xl">
    <div className="rounded-[1.75rem] border border-primary/15 bg-card p-3 shadow-2xl shadow-primary/10 sm:p-5">
      <div className="rounded-2xl border border-border bg-background p-5 sm:p-7">
        <div className="mb-7 flex items-center justify-between"><div><p className="text-xs font-medium text-muted-foreground">Good morning, Alex</p><h3 className="mt-1 text-lg font-semibold tracking-tight">Your financial overview</h3></div><div className="size-9 rounded-full bg-accent" /></div>
        <div className="grid gap-3 sm:grid-cols-3">
          {[['Current balance', '$24,680.42', '+12.4%'], ['Monthly income', '$8,420.00', '+8.2%'], ['Monthly expenses', '$3,186.24', '-4.8%']].map(([label, value, change], i) => <div key={label} className="rounded-xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold tracking-tight">{value}</p><p className={`mt-2 text-xs ${i === 2 ? 'text-primary' : 'text-primary'}`}>{change} <span className="text-muted-foreground">vs last month</span></p></div>)}
        </div>
        <div className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_1fr]">
          <div className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-medium">Spending overview</p><p className="mt-1 text-xs text-muted-foreground">May 2024</p></div><span className="rounded-md bg-accent px-2 py-1 text-xs text-accent-foreground">Last 6 months</span></div><div className="mt-6 flex h-28 items-end gap-2 sm:gap-4">{[38,58,46,76,64,92,70,84,56,68,48,78].map((height, i) => <motion.div key={i} initial={{ height: 0 }} animate={{ height: `${height}%` }} transition={{ delay: .5 + i * .04, duration: .5 }} className={`flex-1 rounded-t-sm ${i === 7 ? 'bg-primary' : 'bg-primary/15'}`} />)}</div><div className="mt-3 flex justify-between text-[10px] text-muted-foreground"><span>Dec</span><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span></div></div>
          <div className="rounded-xl border border-border bg-card p-4"><p className="text-sm font-medium">Savings goal</p><p className="mt-1 text-xs text-muted-foreground">Emergency fund</p><div className="mt-7 flex items-center gap-4"><div className="relative size-20 rounded-full" style={{ background: 'conic-gradient(var(--primary) 72%, var(--accent) 0)' }}><div className="absolute inset-2 flex items-center justify-center rounded-full bg-card text-sm font-semibold">72%</div></div><div><p className="text-lg font-semibold">$7,200</p><p className="text-xs text-muted-foreground">of $10,000 goal</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-accent"><div className="h-full w-[72%] rounded-full bg-primary" /></div></div>
        </div>
      </div>
    </div>
    <motion.div initial={{ opacity: 0, x: -18 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .8 }} className="absolute -left-3 top-12 hidden rounded-xl border border-border bg-card p-4 shadow-xl sm:block lg:-left-20"><p className="text-xs text-muted-foreground">Savings</p><p className="mt-1 text-lg font-semibold">$7,200.00</p><p className="mt-1 text-xs text-primary">+18.6%</p></motion.div>
    <motion.div initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .95 }} className="absolute -right-3 bottom-12 hidden rounded-xl border border-border bg-card p-4 shadow-xl sm:block lg:-right-20"><p className="text-xs text-muted-foreground">Monthly expenses</p><p className="mt-1 text-lg font-semibold">$3,186.24</p><p className="mt-1 text-xs text-primary">Under budget</p></motion.div>
  </motion.div>
}

export default function Landing() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="relative z-20 border-b border-border/70"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link to="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><WalletCards /></span>FinanceFlow</Link><nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#features" className="transition-colors hover:text-foreground">Features</a><a href="#benefits" className="transition-colors hover:text-foreground">Benefits</a><a href="#reports" className="transition-colors hover:text-foreground">Reports</a></nav><div className="hidden items-center gap-3 md:flex"><button className="px-3 py-2 text-sm text-muted-foreground transition-colors hover:text-foreground">Log in</button><Link to="/dashboard" className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-transform hover:-translate-y-0.5">Get started <ArrowRight className="ml-2 inline size-4" /></Link></div><button aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)} className="md:hidden">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="border-t border-border px-5 py-5 md:hidden"><nav className="flex flex-col gap-4 text-sm"><a href="#features" onClick={() => setMenuOpen(false)}>Features</a><a href="#benefits" onClick={() => setMenuOpen(false)}>Benefits</a><a href="#reports" onClick={() => setMenuOpen(false)}>Reports</a><Link to="/dashboard" className="font-medium text-primary">Get started <ArrowRight className="ml-1 inline size-4" /></Link></nav></div>}</header>
    <main><section className="relative px-5 pb-20 pt-20 lg:px-8 lg:pb-28 lg:pt-28"><div className="mx-auto max-w-4xl text-center"><motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-accent px-3 py-1.5 text-xs font-medium text-accent-foreground"><Sparkles className="size-3.5" /> A clearer way to manage your money</motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="text-balance text-5xl font-semibold tracking-[-0.06em] sm:text-6xl lg:text-7xl">Take Control of <span className="text-primary">Your Money</span></motion.h1><motion.p initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .18 }} className="mx-auto mt-6 max-w-2xl text-pretty text-base leading-7 text-muted-foreground sm:text-lg">Track income, understand expenses, build better budgets, and grow your savings — all in one beautifully simple place.</motion.p><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .3 }} className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/dashboard" className="rounded-lg bg-primary px-5 py-3 text-sm font-medium text-primary-foreground transition-transform hover:-translate-y-0.5">Get started <ArrowRight className="ml-2 inline size-4" /></Link><a href="#reports" className="rounded-lg border border-border px-5 py-3 text-sm font-medium transition-colors hover:bg-accent">View dashboard <ChevronRight className="ml-1 inline size-4" /></a></motion.div></div><div className="mx-auto mt-16 max-w-6xl"><DashboardPreview /></div></section>
    <section id="features" className="border-t border-border/70 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="text-sm font-medium text-primary">Everything in one place</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Financial clarity, built into every detail.</h2><p className="mt-4 leading-7 text-muted-foreground">FinanceFlow gives you the tools and the context to make smarter decisions with less effort.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{features.map((feature, i) => <motion.div key={feature.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .05 }} className="bg-card p-7"><feature.icon className="size-5 text-primary" /><h3 className="mt-5 font-medium">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{feature.text}</p></motion.div>)}</div></div></section>
    <section id="benefits" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-medium text-primary">Made for momentum</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Your money should feel less complicated.</h2><p className="mt-5 leading-7 text-muted-foreground">From your first budget to your next big goal, FinanceFlow keeps the signal clear and the noise out.</p><ul className="mt-7 flex flex-col gap-4 text-sm">{['One calm view of your entire financial life','Insights that help you act, not just observe','Private by design, simple by default'].map(item => <li key={item} className="flex items-center gap-3"><span className="flex size-5 items-center justify-center rounded-full bg-accent text-primary"><Check className="size-3.5" /></span>{item}</li>)}</ul></div><div id="reports" className="rounded-2xl border border-border bg-card p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm font-medium">Monthly spending</p><p className="mt-1 text-xs text-muted-foreground">Your spending trend at a glance</p></div><BarChart3 className="size-5 text-primary" /></div><div className="mt-10 flex h-48 items-end gap-3">{[44,58,52,71,62,86,74,93,68,78,56,81].map((h, i) => <motion.div key={i} initial={{ height: 0 }} whileInView={{ height: `${h}%` }} viewport={{ once: true }} transition={{ delay: i * .04 }} className={`flex-1 rounded-t-md ${i === 7 ? 'bg-primary' : 'bg-primary/15'}`} />)}</div><div className="mt-4 flex justify-between text-xs text-muted-foreground"><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span><span>Oct</span><span>Nov</span></div></div></div></section>
    <section className="px-5 pb-20 lg:px-8 lg:pb-28"><div className="mx-auto max-w-7xl rounded-2xl bg-primary px-6 py-14 text-center text-primary-foreground sm:px-12"><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Make every dollar count.</h2><p className="mx-auto mt-4 max-w-xl leading-7 opacity-80">Start building a clearer financial future with FinanceFlow today.</p><Link to="/dashboard" className="mt-8 inline-flex rounded-lg bg-background px-5 py-3 text-sm font-medium text-foreground transition-transform hover:-translate-y-0.5">Get started <ArrowRight className="ml-2 size-4" /></Link></div></section></main>
    <footer className="border-t border-border px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 font-medium text-foreground"><span className="flex size-7 items-center justify-center rounded-lg bg-primary text-primary-foreground"><WalletCards className="size-4" /></span>FinanceFlow</div><p>© 2024 FinanceFlow. Built for better money habits.</p></div></footer>
  </div>
}
export { DashboardPreview }
