import { useMemo, useState } from 'react'
import { motion } from 'motion/react'
import { ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, CircleDollarSign, TrendingUp } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useFinanceContext } from '@/context/FinanceContext'
import type { Transaction } from '@/types/finance'

const colors = ['var(--chart-1)', 'var(--chart-2)', 'var(--chart-3)', 'var(--chart-4)', 'var(--chart-5)']
const money = (value: number, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value)
const monthLabel = (key: string) => new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(new Date(`${key}-01T12:00:00`))
const shortMonth = (key: string) => new Intl.DateTimeFormat('en-US', { month: 'short' }).format(new Date(`${key}-01T12:00:00`))

function ChartTip({ active, payload, label, currency }: { active?: boolean; payload?: Array<{ name?: string; value?: number; color?: string }>; label?: string; currency: string }) {
  if (!active || !payload?.length) return null
  return <div className="rounded-lg border bg-card px-3 py-2 text-xs shadow-lg"><p className="mb-1 font-medium">{label}</p>{payload.map((item) => <p key={item.name} className="flex items-center justify-between gap-4 text-muted-foreground"><span style={{ color: item.color }}>{item.name}</span><span className="font-mono text-foreground">{money(item.value ?? 0, currency)}</span></p>)}</div>
}
function EmptyChart({ label = 'No data for this period' }: { label?: string }) { return <div className="grid h-full place-items-center rounded-lg border border-dashed bg-muted/20 text-sm text-muted-foreground">{label}</div> }
function ChartCard({ title, description, children, className = '' }: { title: string; description: string; children: React.ReactNode; className?: string }) { return <Card className={className}><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card> }
function Donut({ data, total, currency, income = false }: { data: Array<{ name: string; value: number }>; total: number; currency: string; income?: boolean }) { return <div className="flex flex-col items-center gap-5 sm:flex-row"><div className="relative size-44 shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={57} outerRadius={80} paddingAngle={3} strokeWidth={0}>{data.map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip content={<ChartTip currency={currency} />} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="font-mono text-lg font-semibold">{money(total, currency)}</p><p className="text-[11px] text-muted-foreground">{income ? 'received' : 'spent'}</p></div></div></div><div className="flex w-full flex-col gap-2">{data.slice(0, 5).map((item, index) => <div className="flex items-center justify-between gap-3 text-xs" key={item.name}><span className="flex items-center gap-2 text-muted-foreground"><i className="size-2 rounded-full" style={{ backgroundColor: colors[index % colors.length] }} />{item.name}</span><span className="font-mono">{money(item.value, currency)}</span></div>)}</div></div> }

export default function Reports() {
  const { transactions, preferences } = useFinanceContext()
  const keys = useMemo(() => Array.from(new Set([new Date().toISOString().slice(0, 7), ...transactions.map((item) => item.date.slice(0, 7))])).sort().reverse(), [transactions])
  const [selectedMonth, setSelectedMonth] = useState(keys[0])
  const month = keys.includes(selectedMonth) ? selectedMonth : keys[0]
  const scoped = useMemo(() => transactions.filter((item) => item.date.startsWith(month)), [transactions, month])
  const expenses = scoped.filter((item) => item.type === 'expense')
  const income = scoped.filter((item) => item.type === 'income')
  const totalExpenses = expenses.reduce((sum, item) => sum + item.amount, 0)
  const totalIncome = income.reduce((sum, item) => sum + item.amount, 0)
  const categoryData = useMemo(() => Object.entries(expenses.reduce<Record<string, number>>((result, item) => { result[item.category] = (result[item.category] ?? 0) + item.amount; return result }, {})).sort((a, b) => b[1] - a[1]).map(([name, value]) => ({ name, value })), [expenses])
  const incomeData = useMemo(() => Object.entries(income.reduce<Record<string, number>>((result, item) => { result[item.category] = (result[item.category] ?? 0) + item.amount; return result }, {})).map(([name, value]) => ({ name, value })), [income])
  const monthly = useMemo(() => keys.slice(0, 8).reverse().map((key) => { const items = transactions.filter((item) => item.date.startsWith(key)); return { month: shortMonth(key), income: items.filter((item) => item.type === 'income').reduce((s, i) => s + i.amount, 0), expenses: items.filter((item) => item.type === 'expense').reduce((s, i) => s + i.amount, 0), savings: items.reduce((s, i) => s + (i.type === 'income' ? i.amount : -i.amount), 0) } }), [transactions, keys])
  const trend = useMemo(() => [...expenses].sort((a, b) => a.date.localeCompare(b.date)).reduce<Array<{ date: string; amount: number }>>((result, item) => { const previous = result.length ? result[result.length - 1].amount : 0; result.push({ date: item.date.slice(8), amount: previous + item.amount }); return result }, []), [expenses])
  const topTransactions = [...scoped].sort((a, b) => b.amount - a.amount).slice(0, 5)
  const savings = totalIncome - totalExpenses
  const rate = totalIncome ? Math.round((savings / totalIncome) * 100) : 0
  const formatDate = (date: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(new Date(`${date}T12:00:00`))
  return <div className="mx-auto flex max-w-[1500px] flex-col gap-6 p-5 md:gap-8 md:p-8">
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Financial intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">Reports & insights</h1><p className="mt-2 text-muted-foreground">Understand the patterns behind your financial decisions.</p></div><Select value={month} onValueChange={(value) => { if (value) setSelectedMonth(value) }}><SelectTrigger aria-label="Select report month" className="w-full sm:w-44"><CalendarDays data-icon="inline-start" /><SelectValue /></SelectTrigger><SelectContent>{keys.map((key) => <SelectItem value={key} key={key}>{monthLabel(key)}</SelectItem>)}</SelectContent></Select></motion.div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: 'Income', value: totalIncome, icon: ArrowDownLeft, tone: 'text-chart-2' }, { label: 'Expenses', value: totalExpenses, icon: ArrowUpRight, tone: 'text-destructive' }, { label: 'Net savings', value: savings, icon: CircleDollarSign, tone: 'text-primary' }, { label: 'Savings rate', value: rate, icon: TrendingUp, tone: 'text-chart-4', suffix: '%' }].map(({ label, value, icon: Icon, tone, suffix }) => <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} key={label}><Card><CardContent className="flex items-center gap-4 p-5"><div className={`grid size-11 place-items-center rounded-xl bg-muted ${tone}`}><Icon /></div><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 font-mono text-2xl font-semibold">{suffix ? `${value}${suffix}` : money(value, preferences.currency)}</p><p className="mt-1 text-xs text-muted-foreground">{monthLabel(month)}</p></div></CardContent></Card></motion.div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><ChartCard title="Income vs expenses" description="Monthly cash flow across your available history."><div className="h-64">{monthly.some((item) => item.income || item.expenses) ? <ResponsiveContainer width="100%" height="100%"><BarChart data={monthly} barGap={8}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }} tickFormatter={(value) => `$${value / 1000}k`} /><Tooltip content={<ChartTip currency={preferences.currency} />} /><Bar dataKey="income" fill="var(--chart-2)" radius={[4, 4, 0, 0]} /><Bar dataKey="expenses" fill="var(--primary)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer> : <EmptyChart />}</div><div className="mt-3 flex gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-chart-2" />Income</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-primary" />Expenses</span></div></ChartCard><ChartCard title="Savings trajectory" description="Net savings generated each month."><div className="h-64">{monthly.some((item) => item.savings) ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly}><defs><linearGradient id="savingsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--chart-4)" stopOpacity={0.3} /><stop offset="1" stopColor="var(--chart-4)" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }} /><Tooltip content={<ChartTip currency={preferences.currency} />} /><Area type="monotone" dataKey="savings" stroke="var(--chart-4)" fill="url(#savingsFill)" strokeWidth={2} /></AreaChart></ResponsiveContainer> : <EmptyChart />}</div></ChartCard></div>
    <div className="grid gap-6 lg:grid-cols-2"><ChartCard title="Spending by category" description={`Your ${monthLabel(month)} expense mix.`}>{categoryData.length ? <Donut data={categoryData} total={totalExpenses} currency={preferences.currency} /> : <div className="grid h-44 place-items-center text-sm text-muted-foreground">No expenses recorded.</div>}</ChartCard><ChartCard title="Income sources" description={`Where your ${monthLabel(month)} income came from.`}>{incomeData.length ? <Donut data={incomeData} total={totalIncome} currency={preferences.currency} income /> : <div className="grid h-44 place-items-center text-sm text-muted-foreground">No income recorded.</div>}</ChartCard></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><ChartCard title="Expense trend" description="Cumulative spending through the month."><div className="h-56">{trend.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="date" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} tickFormatter={(value) => `$${value}`} /><Tooltip content={<ChartTip currency={preferences.currency} />} /><Line type="monotone" dataKey="amount" stroke="var(--primary)" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer> : <EmptyChart />}</div></ChartCard><ChartCard title="Highest transactions" description="Largest transactions in the selected month."><div className="flex flex-col gap-1">{topTransactions.length ? topTransactions.map((item: Transaction, index) => <div className="flex items-center gap-3 rounded-lg px-2 py-3 transition-colors hover:bg-muted/60" key={item.id}><span className="grid size-7 place-items-center rounded-md bg-muted font-mono text-xs text-muted-foreground">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.category} · {formatDate(item.date)}</p></div><Badge variant={item.type === 'income' ? 'default' : 'secondary'}>{item.type === 'income' ? '+' : '-'}{money(item.amount, preferences.currency)}</Badge></div>) : <div className="grid h-44 place-items-center text-sm text-muted-foreground">No transactions recorded.</div>}</div></ChartCard></div>
    <div className="flex items-center gap-2 border-t pt-4 text-xs text-muted-foreground"><BarChart3 className="size-4" />Reports are calculated from your Ledgerly transactions. <Button variant="link" className="h-auto p-0 text-xs">View transactions</Button></div>
  </div>
}

export { Reports }
