import React, { useState } from 'react'
import { AlertTriangle, Download, Moon, RotateCcw, Settings2, Sun, Trash2, Monitor } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { useFinanceContext } from '@/context/FinanceContext'
import { useTheme, type Theme } from '@/context/ThemeContext'
import { useLocalStorage } from '@/hooks/useLocalStorage'

const currencyOptions = ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY']

export default function Settings() {
  const { transactions, budgets, categories, preferences, setPreferences, resetDemoData, clearTransactions, clearBudgets } = useFinanceContext()
  const { theme, setTheme } = useTheme()
  const [profile, setProfile] = useLocalStorage('ledgerly-profile', { name: 'Alex Morgan', email: 'alex@example.com' })
  const [defaultCategory, setDefaultCategory] = useLocalStorage('ledgerly-default-category', 'Food')
  const [message, setMessage] = useState('')
  const notify = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(''), 3500) }
  const exportTransactions = () => { const rows = [['Date', 'Title', 'Type', 'Category', 'Amount', 'Description'], ...transactions.map((t) => [t.date, t.title, t.type, t.category, t.amount, t.description || ''])]; const csv = rows.map((row) => row.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\r\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'ledgerly-transactions.csv'; link.click(); notify('Transactions exported successfully.') }
  const confirmAction = (action: () => void, text: string) => { action(); notify(text) }
  return <main className="mx-auto flex w-full max-w-4xl flex-col gap-6 p-4 pb-8 sm:p-5 md:gap-8 md:p-8">
    <header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Settings</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Make Ledgerly yours</h1><p className="mt-2 text-muted-foreground">Your preferences are saved automatically on this device.</p></header>
    <Card><CardHeader><CardTitle>Profile</CardTitle><CardDescription>Personal details used across your workspace.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label htmlFor="name">Name</Label><Input id="name" value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} /></div><div className="grid gap-2"><Label htmlFor="email">Email</Label><Input id="email" type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} /></div><div className="grid gap-2"><Label>Currency</Label><Select value={preferences.currency} onValueChange={(v) => v && setPreferences({ currency: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{currencyOptions.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 data-icon="inline-start" /> Appearance</CardTitle><CardDescription>Choose how the interface looks on this device.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{([['light', Sun, 'Light'], ['dark', Moon, 'Dark'], ['system', Monitor, 'System']] as const).map(([value, Icon, label]) => <Button key={value} variant={theme === value ? 'default' : 'outline'} className="justify-start" onClick={() => setTheme(value)}><Icon data-icon="inline-start" />{label}</Button>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Finance preferences</CardTitle><CardDescription>Set defaults for new transactions and budgets.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>Default currency</Label><Select value={preferences.currency} onValueChange={(v) => v && setPreferences({ currency: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{currencyOptions.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Default transaction category</Label><Select value={defaultCategory} onValueChange={(v) => v && setDefaultCategory(v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{categories.filter((c) => c.type === 'expense').map((c) => <SelectItem key={c.id} value={c.name}>{c.name}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Data management</CardTitle><CardDescription>Export or permanently remove local Ledgerly data.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><Button variant="outline" onClick={exportTransactions}><Download data-icon="inline-start" /> Export transactions ({transactions.length})</Button><DangerAction title="Reset demo data" description="Restore sample transactions, budgets, categories, and preferences. This cannot be undone." icon={<RotateCcw data-icon="inline-start" />} onConfirm={() => confirmAction(resetDemoData, 'Demo data reset.')} /><DangerAction title="Clear all transactions" description="Permanently delete every transaction from this device." icon={<Trash2 data-icon="inline-start" />} onConfirm={() => confirmAction(clearTransactions, 'All transactions cleared.')} /><DangerAction title="Clear all budgets" description="Permanently delete every budget from this device." icon={<Trash2 data-icon="inline-start" />} onConfirm={() => confirmAction(clearBudgets, 'All budgets cleared.')} /></CardContent></Card>
    <Card><CardHeader><CardTitle>About</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm text-muted-foreground"><p><span className="font-medium text-foreground">Application version:</span> 1.0.0</p><p><span className="font-medium text-foreground">Technology stack:</span> React, TypeScript, Vite, Tailwind CSS, shadcn/ui</p></CardContent></Card>
    {message && <p role="status" aria-live="polite" className="fixed bottom-5 right-5 z-50 rounded-lg border bg-card px-4 py-3 text-sm font-medium shadow-lg">{message}</p>}
  </main>
}
function DangerAction({ title, description, icon, onConfirm }: { title: string; description: string; icon: React.ReactNode; onConfirm: () => void }) { return <AlertDialog><AlertDialogTrigger render={<Button variant="destructive" className="justify-start" />}><AlertTriangle data-icon="inline-start" />{title}</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}?</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={onConfirm}>{icon} Confirm</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> }
