import { useMemo, useState } from 'react'
import { Search, Plus, MoreHorizontal, Pencil, Trash2, Eye, ReceiptText, Download, SlidersHorizontal, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useFinance } from '@/hooks/useFinance'
import { TransactionForm } from '@/components/transactions/TransactionForm'
import type { Transaction, TransactionType } from '@/types/finance'

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })
export default function Transactions() {
  const { transactions, categories, addTransaction, updateTransaction, deleteTransaction } = useFinance()
  const [query, setQuery] = useState(''); const [type, setType] = useState<'all' | TransactionType>('all'); const [category, setCategory] = useState('all'); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState(''); const [minAmount, setMinAmount] = useState(''); const [maxAmount, setMaxAmount] = useState(''); const [sort, setSort] = useState('newest'); const [filtersOpen, setFiltersOpen] = useState(false); const [editing, setEditing] = useState<Transaction>(); const [formOpen, setFormOpen] = useState(false); const [deleting, setDeleting] = useState<Transaction>(); const [viewing, setViewing] = useState<Transaction>(); const [notice, setNotice] = useState('')
  const clearFilters = () => { setQuery(''); setType('all'); setCategory('all'); setFromDate(''); setToDate(''); setMinAmount(''); setMaxAmount(''); setSort('newest') }
  const filterControls = <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><div className="relative md:col-span-2 lg:col-span-4"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search title, description, or category..." value={query} onChange={(e) => setQuery(e.target.value)} /></div><Select value={type} onValueChange={(v) => v && setType(v as typeof type)}><SelectTrigger><SelectValue placeholder="Type" /></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem><SelectItem value="income">Income</SelectItem><SelectItem value="expense">Expense</SelectItem></SelectContent></Select><Select value={category} onValueChange={(v) => v && setCategory(v)}><SelectTrigger><SelectValue placeholder="Category" /></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{categories.map((c) => <SelectItem key={c.id} value={c.name}>{c.name}</SelectItem>)}</SelectContent></Select><Input type="date" aria-label="From date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} /><Input type="date" aria-label="To date" value={toDate} onChange={(e) => setToDate(e.target.value)} /><Input type="number" min="0" aria-label="Minimum amount" placeholder="Min amount" value={minAmount} onChange={(e) => setMinAmount(e.target.value)} /><Input type="number" min="0" aria-label="Maximum amount" placeholder="Max amount" value={maxAmount} onChange={(e) => setMaxAmount(e.target.value)} /><Select value={sort} onValueChange={(v) => v && setSort(v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="newest">Newest</SelectItem><SelectItem value="oldest">Oldest</SelectItem><SelectItem value="highest">Highest amount</SelectItem><SelectItem value="lowest">Lowest amount</SelectItem><SelectItem value="az">A-Z</SelectItem><SelectItem value="za">Z-A</SelectItem></SelectContent></Select><Button type="button" variant="ghost" onClick={clearFilters}><X data-icon="inline-start" /> Clear filters</Button></div>
  const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); const result = transactions.filter((t) => (!normalized || `${t.title} ${t.description} ${t.category}`.toLowerCase().includes(normalized)) && (type === 'all' || t.type === type) && (category === 'all' || t.category === category) && (!fromDate || t.date >= fromDate) && (!toDate || t.date <= toDate) && (!minAmount || t.amount >= Number(minAmount)) && (!maxAmount || t.amount <= Number(maxAmount))); return result.sort((a, b) => sort === 'oldest' ? a.date.localeCompare(b.date) : sort === 'highest' ? b.amount - a.amount : sort === 'lowest' ? a.amount - b.amount : sort === 'az' ? a.title.localeCompare(b.title) : sort === 'za' ? b.title.localeCompare(a.title) : b.date.localeCompare(a.date)) }, [transactions, query, type, category, fromDate, toDate, minAmount, maxAmount, sort])
  const submit = (values: Omit<Transaction, 'id' | 'createdAt'>) => { editing ? updateTransaction(editing.id, values) : addTransaction(values); setFormOpen(false); setEditing(undefined) }
  const openEdit = (transaction: Transaction) => { setEditing(transaction); setFormOpen(true) }
  const exportCsv = () => { const escape = (value: string | number) => `"${String(value ?? '').replace(/"/g, '""')}"`; const rows = [['Date', 'Title', 'Type', 'Category', 'Amount', 'Description'], ...filtered.map((t) => [t.date, t.title, t.type === 'income' ? 'Income' : 'Expense', t.category, t.amount, t.description || ''])]; const csv = rows.map((row) => row.map(escape).join(',')).join('\\r\\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `finance-transactions-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); setNotice(`${filtered.length} transaction${filtered.length === 1 ? '' : 's'} exported successfully`); window.setTimeout(() => setNotice(''), 3500) }
  return <main className="mx-auto flex max-w-7xl flex-col gap-6 p-5 md:p-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Money movement</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Transactions</h1><p className="mt-2 text-muted-foreground">Search, filter, and manage your financial activity.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportCsv} disabled={!filtered.length}><Download data-icon="inline-start" /> Export CSV</Button><Button onClick={() => { setEditing(undefined); setFormOpen(true) }}><Plus data-icon="inline-start" /> Add transaction</Button></div></header>
    <Card><CardHeader className="gap-4"><div className="flex items-center justify-between gap-3"><CardTitle className="text-base">All activity <span className="ml-2 text-sm font-normal text-muted-foreground">Showing {filtered.length} of {transactions.length} transactions</span></CardTitle><Button className="md:hidden" variant="outline" onClick={() => setFiltersOpen(true)}><SlidersHorizontal data-icon="inline-start" /> Filters</Button></div><div className="hidden md:block">{filterControls}</div><Dialog open={filtersOpen} onOpenChange={setFiltersOpen}><DialogContent><DialogHeader><DialogTitle>Filter transactions</DialogTitle><DialogDescription>Refine your financial activity without leaving this page.</DialogDescription></DialogHeader>{filterControls}<Button onClick={() => setFiltersOpen(false)}>Show {filtered.length} transactions</Button></DialogContent></Dialog></CardHeader><CardContent>{filtered.length === 0 ? <div className="flex min-h-64 flex-col items-center justify-center gap-3 text-center"><ReceiptText className="size-10 text-muted-foreground" /><h2 className="text-lg font-semibold">No transactions found</h2><p className="text-sm text-muted-foreground">Try adjusting your filters or add your first transaction.</p><Button onClick={() => setFormOpen(true)}>Add transaction</Button></div> : <><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Transaction</TableHead><TableHead>Category</TableHead><TableHead>Type</TableHead><TableHead>Date</TableHead><TableHead className="text-right">Amount</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{filtered.map((t) => <TableRow key={t.id}><TableCell><div className="font-medium">{t.title}</div><div className="text-xs text-muted-foreground">{t.description}</div></TableCell><TableCell>{t.category}</TableCell><TableCell><Badge variant={t.type === 'income' ? 'default' : 'secondary'}>{t.type}</Badge></TableCell><TableCell>{new Date(`${t.date}T12:00:00`).toLocaleDateString()}</TableCell><TableCell className={`text-right font-semibold ${t.type === 'income' ? 'text-primary' : ''}`}>{t.type === 'income' ? '+' : '-'}{money.format(t.amount)}</TableCell><TableCell><Actions transaction={t} onEdit={openEdit} onDelete={setDeleting} onView={setViewing} /></TableCell></TableRow>)}</TableBody></Table></div><div className="flex flex-col gap-3 md:hidden">{filtered.map((t) => <div key={t.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{t.title}</p><p className="text-xs text-muted-foreground">{t.category} · {new Date(`${t.date}T12:00:00`).toLocaleDateString()}</p></div><Actions transaction={t} onEdit={openEdit} onDelete={setDeleting} onView={setViewing} /></div><p className={`mt-4 text-lg font-semibold ${t.type === 'income' ? 'text-primary' : ''}`}>{t.type === 'income' ? '+' : '-'}{money.format(t.amount)}</p></div>)}</div></>}</CardContent></Card>
    <Dialog open={formOpen} onOpenChange={setFormOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? 'Edit transaction' : 'Add transaction'}</DialogTitle><DialogDescription>Keep your financial records accurate and up to date.</DialogDescription></DialogHeader><TransactionForm categories={categories} initial={editing} onSubmit={submit} onCancel={() => setFormOpen(false)} /></DialogContent></Dialog>
    <AlertDialog open={!!deleting} onOpenChange={(open) => !open && setDeleting(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete transaction?</AlertDialogTitle><AlertDialogDescription>This will permanently remove {deleting?.title} from your records.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => { if (deleting) deleteTransaction(deleting.id); setDeleting(undefined) }}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={!!viewing} onOpenChange={(open) => !open && setViewing(undefined)}><DialogContent><DialogHeader><DialogTitle>{viewing?.title}</DialogTitle><DialogDescription>{viewing?.description || 'No description provided.'}</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Amount</p><p className="font-semibold">{viewing && money.format(viewing.amount)}</p></div><div><p className="text-muted-foreground">Type</p><p className="font-semibold capitalize">{viewing?.type}</p></div><div><p className="text-muted-foreground">Category</p><p className="font-semibold">{viewing?.category}</p></div><div><p className="text-muted-foreground">Date</p><p className="font-semibold">{viewing?.date}</p></div></div></DialogContent></Dialog>
  {notice && <div role="status" aria-live="polite" className="fixed bottom-5 right-5 z-50 rounded-lg border bg-card px-4 py-3 text-sm font-medium text-card-foreground shadow-lg">{notice}</div>}
  </main>
}
function Actions({ transaction, onEdit, onDelete, onView }: { transaction: Transaction; onEdit: (t: Transaction) => void; onDelete: (t: Transaction) => void; onView: (t: Transaction) => void }) { return <DropdownMenu><DropdownMenuTrigger><MoreHorizontal aria-label={`Actions for ${transaction.title}`} /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => onView(transaction)}><Eye /> View details</DropdownMenuItem><DropdownMenuItem onClick={() => onEdit(transaction)}><Pencil /> Edit</DropdownMenuItem><DropdownMenuItem className="text-destructive" onClick={() => onDelete(transaction)}><Trash2 /> Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu> }
