import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import { supabase } from '@/lib/supabase'
import { useLocalStorage } from '@/hooks/useLocalStorage'
import type { Budget, Category, DateRange, FinancialSummary, MonthlyTotal, Transaction, TransactionType } from '@/types/finance'

export const seedTransactions: Transaction[] = []
export const seedBudgets: Budget[] = []
export const seedCategories: Category[] = [
  { id: 'c-1', name: 'Food', type: 'expense', icon: 'utensils' }, { id: 'c-2', name: 'Transport', type: 'expense', icon: 'car' },
  { id: 'c-3', name: 'Bills', type: 'expense', icon: 'receipt' }, { id: 'c-4', name: 'Entertainment', type: 'expense', icon: 'popcorn' }, { id: 'c-5', name: 'Income', type: 'income', icon: 'wallet' },
]
type EntityInput<T> = Omit<T, 'id' | 'createdAt'>
export interface UserPreferences { currency: string; firstDayOfWeek: number; compactMode: boolean }
interface FinanceContextValue { transactions: Transaction[]; budgets: Budget[]; categories: Category[]; preferences: UserPreferences; addTransaction: (input: EntityInput<Transaction>) => Transaction; updateTransaction: (id: string, updates: Partial<EntityInput<Transaction>>) => void; deleteTransaction: (id: string) => void; addBudget: (input: EntityInput<Budget>) => Budget; updateBudget: (id: string, updates: Partial<EntityInput<Budget>>) => void; deleteBudget: (id: string) => void; setPreferences: (updates: Partial<UserPreferences>) => void; resetDemoData: () => void; clearTransactions: () => void; clearBudgets: () => void; getBalance: () => number; getTotalIncome: () => number; getTotalExpenses: () => number; getTotalSavings: () => number; getExpensesByCategory: () => Record<string, number>; getMonthlyExpenses: () => MonthlyTotal[]; getMonthlyIncome: () => MonthlyTotal[]; getSummary: () => FinancialSummary; searchTransactions: (query: string) => Transaction[]; filterByCategory: (category: string) => Transaction[]; filterByType: (type: TransactionType) => Transaction[]; filterByDate: (range: DateRange) => Transaction[] }
const FinanceContext = createContext<FinanceContextValue | null>(null)
const defaultPreferences: UserPreferences = { currency: 'USD', firstDayOfWeek: 0, compactMode: false }
const makeId = (prefix: string) => `${prefix}-${crypto.randomUUID()}`

export function FinanceProvider({ children }: { children: ReactNode }) {
  const [transactions, setTransactions] = useLocalStorage<Transaction[]>('ledgerly-transactions', seedTransactions)
  const [budgets, setBudgets] = useLocalStorage<Budget[]>('ledgerly-budgets', seedBudgets)
  const [categories, setCategories] = useLocalStorage<Category[]>('ledgerly-categories', seedCategories)
  const [preferences, setPreferencesState] = useLocalStorage('ledgerly-preferences', defaultPreferences)
  const [userId, setUserId] = useState<string>()
  useEffect(() => { let active = true; (async () => { const { data } = await supabase.auth.getSession(); let user = data.session?.user; if (!user) { const result = await supabase.auth.signInAnonymously(); user = result.data.user ?? undefined } if (!active || !user) return; setUserId(user.id); const [tx, bg, cats, prefs] = await Promise.all([supabase.from('transactions').select('id,title,amount,type,category,date,description,created_at').order('date', { ascending: false }), supabase.from('budgets').select('id,category,limit_amount,spent,month,year'), supabase.from('categories').select('id,name,type,icon'), supabase.from('user_preferences').select('currency,first_day_of_week,compact_mode').eq('user_id', user.id).maybeSingle()]); if (tx.data) setTransactions(tx.data.map((item) => ({ ...item, createdAt: item.created_at }))); if (bg.data) setBudgets(bg.data.map((item) => ({ ...item, limit: Number(item.limit_amount) }))); if (cats.data?.length) setCategories(cats.data); if (prefs.data) setPreferencesState({ currency: prefs.data.currency, firstDayOfWeek: prefs.data.first_day_of_week, compactMode: prefs.data.compact_mode }) })(); return () => { active = false } }, [setTransactions, setBudgets, setCategories, setPreferencesState])
  const persist = useCallback((table: string, payload: Record<string, unknown>) => { if (userId) void supabase.from(table).upsert({ ...payload, user_id: userId }) }, [userId])
  const addTransaction = useCallback((input: EntityInput<Transaction>) => { const item = { ...input, id: makeId('t'), createdAt: new Date().toISOString() }; setTransactions((current) => [item, ...current]); persist('transactions', { id: item.id, title: item.title, amount: item.amount, type: item.type, category: item.category, date: item.date, description: item.description }); return item }, [setTransactions, persist])
  const updateTransaction = useCallback((id: string, updates: Partial<EntityInput<Transaction>>) => { setTransactions((current) => current.map((item) => item.id === id ? { ...item, ...updates } : item)); if (userId) void supabase.from('transactions').update({ ...updates, updated_at: new Date().toISOString() }).eq('id', id).eq('user_id', userId) }, [setTransactions, userId])
  const deleteTransaction = useCallback((id: string) => { setTransactions((current) => current.filter((item) => item.id !== id)); if (userId) void supabase.from('transactions').delete().eq('id', id).eq('user_id', userId) }, [setTransactions, userId])
  const addBudget = useCallback((input: EntityInput<Budget>) => { const item = { ...input, id: makeId('b') }; setBudgets((current) => [item, ...current]); persist('budgets', { id: item.id, category: item.category, limit_amount: item.limit, spent: item.spent, month: item.month, year: item.year }); return item }, [setBudgets, persist])
  const updateBudget = useCallback((id: string, updates: Partial<EntityInput<Budget>>) => { setBudgets((current) => current.map((item) => item.id === id ? { ...item, ...updates } : item)); if (userId) void supabase.from('budgets').update({ ...(updates.limit !== undefined ? { limit_amount: updates.limit } : updates), updated_at: new Date().toISOString() }).eq('id', id).eq('user_id', userId) }, [setBudgets, userId])
  const deleteBudget = useCallback((id: string) => { setBudgets((current) => current.filter((item) => item.id !== id)); if (userId) void supabase.from('budgets').delete().eq('id', id).eq('user_id', userId) }, [setBudgets, userId])
  const setPreferences = useCallback((updates: Partial<UserPreferences>) => { setPreferencesState((current) => ({ ...current, ...updates })); if (userId) void supabase.from('user_preferences').upsert({ user_id: userId, currency: updates.currency, first_day_of_week: updates.firstDayOfWeek, compact_mode: updates.compactMode }) }, [setPreferencesState, userId])
  const clearTransactions = useCallback(() => { setTransactions([]); if (userId) void supabase.from('transactions').delete().eq('user_id', userId) }, [setTransactions, userId]); const clearBudgets = useCallback(() => { setBudgets([]); if (userId) void supabase.from('budgets').delete().eq('user_id', userId) }, [setBudgets, userId]); const resetDemoData = useCallback(() => { clearTransactions(); clearBudgets(); setCategories(seedCategories) }, [clearTransactions, clearBudgets, setCategories])
  const getTotalIncome = useCallback(() => transactions.filter((i) => i.type === 'income').reduce((s, i) => s + i.amount, 0), [transactions]); const getTotalExpenses = useCallback(() => transactions.filter((i) => i.type === 'expense').reduce((s, i) => s + i.amount, 0), [transactions]); const getBalance = useCallback(() => getTotalIncome() - getTotalExpenses(), [getTotalIncome, getTotalExpenses]); const getExpensesByCategory = useCallback(() => transactions.filter((i) => i.type === 'expense').reduce<Record<string, number>>((r, i) => { r[i.category] = (r[i.category] ?? 0) + i.amount; return r }, {}), [transactions]); const monthly = useCallback((type: TransactionType) => Object.entries(transactions.filter((i) => i.type === type).reduce<Record<string, number>>((r, i) => { const k = i.date.slice(0, 7); r[k] = (r[k] ?? 0) + i.amount; return r }, {})).sort(([a], [b]) => a.localeCompare(b)).map(([month, total]) => ({ month, total })), [transactions]); const getMonthlyExpenses = useCallback(() => monthly('expense'), [monthly]); const getMonthlyIncome = useCallback(() => monthly('income'), [monthly]); const getSummary = useCallback(() => ({ balance: getBalance(), income: getTotalIncome(), expenses: getTotalExpenses(), savings: getBalance() }), [getBalance, getTotalIncome, getTotalExpenses]); const searchTransactions = useCallback((q: string) => { const v = q.trim().toLowerCase(); return v ? transactions.filter((i) => `${i.title} ${i.description} ${i.category}`.toLowerCase().includes(v)) : transactions }, [transactions]); const filterByCategory = useCallback((c: string) => c === 'all' ? transactions : transactions.filter((i) => i.category === c), [transactions]); const filterByType = useCallback((t: TransactionType) => transactions.filter((i) => i.type === t), [transactions]); const filterByDate = useCallback((range: DateRange) => transactions.filter((i) => (!range.from || i.date >= range.from) && (!range.to || i.date <= range.to)), [transactions])
  const value = useMemo(() => ({ transactions, budgets, categories, preferences, addTransaction, updateTransaction, deleteTransaction, addBudget, updateBudget, deleteBudget, setPreferences, resetDemoData, clearTransactions, clearBudgets, getBalance, getTotalIncome, getTotalExpenses, getTotalSavings: getBalance, getExpensesByCategory, getMonthlyExpenses, getMonthlyIncome, getSummary, searchTransactions, filterByCategory, filterByType, filterByDate }), [transactions, budgets, categories, preferences, addTransaction, updateTransaction, deleteTransaction, addBudget, updateBudget, deleteBudget, setPreferences, resetDemoData, clearTransactions, clearBudgets, getBalance, getTotalIncome, getTotalExpenses, getExpensesByCategory, getMonthlyExpenses, getMonthlyIncome, getSummary, searchTransactions, filterByCategory, filterByType, filterByDate])
  return <FinanceContext.Provider value={value}>{children}</FinanceContext.Provider>
}
export function useFinanceContext() { const context = useContext(FinanceContext); if (!context) throw new Error('useFinanceContext must be used within FinanceProvider'); return context }
